Repository DomMorello/git_flow_test, pull requests merged in 2021-07, with the labels that each got.

#2 Navbar ㅇㄴㄴㅁ
  hello.js
  mainpage.js
Labels: bug

#9 ddong aksem만들었따
  ddongddong
Labels: help wanted

#11 again close #10
  test.js
Labels: enhancement

#12 Mainpage
  last_PR.ja
  test.js
Labels: documentation
